[[LMDB]]
arch = "aarch64"
git-tree-sha1 = "4062c0e3d72db624d14e0973c545854f2e760aa7"
libc = "glibc"
os = "linux"

    [[LMDB.download]]
    sha256 = "47a732dd64033ed78993d2c2411c58ca4e014130449463210334f8f3c9578d45"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.aarch64-linux-gnu.tar.gz"
[[LMDB]]
arch = "aarch64"
git-tree-sha1 = "723dad158eb6296864b9e4d5ef01b912b38af274"
libc = "musl"
os = "linux"

    [[LMDB.download]]
    sha256 = "852f338a5444b70389a77bb6587b3e6526b2d441d04f18b74887bc87b0b77219"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.aarch64-linux-musl.tar.gz"
[[LMDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7587583a1794e9b557e98e16ce9c229fb3ca8043"
libc = "glibc"
os = "linux"

    [[LMDB.download]]
    sha256 = "305e83b0fdeb8785b739e14a7f37c7f3924562f6168621236a7ba973b2e911a4"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.armv7l-linux-gnueabihf.tar.gz"
[[LMDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4567f459157bb7f1ef591853e8597d546ce7eaab"
libc = "musl"
os = "linux"

    [[LMDB.download]]
    sha256 = "88073e96326360b1f93b844470361f0781aadb6376793794678e7cd9ef7c2f54"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.armv7l-linux-musleabihf.tar.gz"
[[LMDB]]
arch = "i686"
git-tree-sha1 = "06fba1dde62fa7b6b057d45f759a5fad0f7fc622"
libc = "glibc"
os = "linux"

    [[LMDB.download]]
    sha256 = "1a70cbe691e8f4b6e9aaf34609c7bca63428e7faf34590a0952e977f2dde178e"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.i686-linux-gnu.tar.gz"
[[LMDB]]
arch = "i686"
git-tree-sha1 = "abe776bed5ab6e5756934e644b069bd46fb8ce2f"
libc = "musl"
os = "linux"

    [[LMDB.download]]
    sha256 = "89d43f7ccb25df601d5a56a433cbd4391ec2226c0328790a130531fc7af598e9"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.i686-linux-musl.tar.gz"
[[LMDB]]
arch = "i686"
git-tree-sha1 = "5e059d2bbf8dd500b13a33c4b6e5dd28ca3719fd"
os = "windows"

    [[LMDB.download]]
    sha256 = "94fd95e67853084650321dea594bd769053b51fd12a8f788a420234b15af5bb1"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.i686-w64-mingw32.tar.gz"
[[LMDB]]
arch = "powerpc64le"
git-tree-sha1 = "bd9556184ffb8d3d917edfe44055d2b1d0919782"
libc = "glibc"
os = "linux"

    [[LMDB.download]]
    sha256 = "525fc316999901a8195b8cf99b6c05b3a7246e1f9f626400c3104bbd7dc8fda5"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.powerpc64le-linux-gnu.tar.gz"
[[LMDB]]
arch = "x86_64"
git-tree-sha1 = "fb46a009e99e8c80824bad1f1645f774e644035c"
os = "macos"

    [[LMDB.download]]
    sha256 = "72eb0f9bfaedc72784567b8f110eb0f5525938466504f316b942697dbfced925"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.x86_64-apple-darwin.tar.gz"
[[LMDB]]
arch = "x86_64"
git-tree-sha1 = "6a719a1ac3f0074562aab2d0d30d58b2eacd6ed4"
libc = "glibc"
os = "linux"

    [[LMDB.download]]
    sha256 = "9898c6b3f037a5aac86e8566cc69553a9c3c195afe393401776f6b1163af353d"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.x86_64-linux-gnu.tar.gz"
[[LMDB]]
arch = "x86_64"
git-tree-sha1 = "95bbf0efa063bd7ec9974cc8ec7e593b379f71d7"
libc = "musl"
os = "linux"

    [[LMDB.download]]
    sha256 = "c1ada582c1fcd016f5eb8d326f4d55635b96920836922cb7513be9afacf9a8a9"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.x86_64-linux-musl.tar.gz"
[[LMDB]]
arch = "x86_64"
git-tree-sha1 = "7d9d37af699e8385cc6ca6ab74091d90ceea1b12"
os = "freebsd"

    [[LMDB.download]]
    sha256 = "e83fcc6c5926aab7f6433bb718a838552fe6192fc3225d3650eb1fb21433c8ab"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.x86_64-unknown-freebsd.tar.gz"
[[LMDB]]
arch = "x86_64"
git-tree-sha1 = "a140d7437ecf0a7d862d1af8e8dc5c88db808948"
os = "windows"

    [[LMDB.download]]
    sha256 = "63d70728e4d7c824061e26dc0fb0e5af4f92813815a3c2ad9f6b692d0204f5dc"
    url = "https://github.com/JuliaBinaryWrappers/LMDB_jll.jl/releases/download/LMDB-v0.9.27+0/LMDB.v0.9.27.x86_64-w64-mingw32.tar.gz"
