# Autogenerated wrapper script for LMDB_jll for i686-w64-mingw32
export liblmdb, mdb_copy, mdb_dump, mdb_load, mdb_stat

JLLWrappers.@generate_wrapper_header("LMDB")
JLLWrappers.@declare_library_product(liblmdb, "liblmdb.dll")
JLLWrappers.@declare_executable_product(mdb_copy)
JLLWrappers.@declare_executable_product(mdb_dump)
JLLWrappers.@declare_executable_product(mdb_load)
JLLWrappers.@declare_executable_product(mdb_stat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblmdb,
        "bin\\liblmdb.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mdb_copy,
        "bin\\mdb_copy.exe",
    )

    JLLWrappers.@init_executable_product(
        mdb_dump,
        "bin\\mdb_dump.exe",
    )

    JLLWrappers.@init_executable_product(
        mdb_load,
        "bin\\mdb_load.exe",
    )

    JLLWrappers.@init_executable_product(
        mdb_stat,
        "bin\\mdb_stat.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
